a ="pabavs pdvfgvdsf"
print(a.capitalize())
print((a.lower()))
print(" ".join(a))
print(a.endswith("p"))
print(a.split(" "))
print(a.count("p"))
print(a.partition("a"))
print(a.replace("p","r"))
print(a.expandtabs())
print(a.split("d"))
print(a.index("d"))
